name: rock_paper_scissors_mobile
description: Flatter part of rock_paper_scissors CNN project




version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  image: ^4.0.17
  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.10.4
  path: ^1.8.3
  path_provider: ^2.0.15
  image_picker: ^0.8.8
  
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
  

